[package]
name = "rsonpath"
version = "0.6.1"
authors = ["Mateusz Gienieczko <mat@gienieczko.com>"]
edition = "2021"
description = "Blazing fast JSONPath CLI tool powered by SIMD"
readme = "../../README.md"
license = "MIT"
keywords = ["json", "jsonpath", "query", "simd", "cli"]
categories = [
    "command-line-utilities",
    "text-processing",
    "parser-implementations",
]
repository = "https://github.com/V0ldek/rsonpath"
rust-version = "1.70"
build = "build.rs"

[[bin]]
bench = false
path = "./src/main.rs"
name = "rq"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
clap = { version = "4.4.2", features = ["derive", "wrap_help"] }
color-eyre = { version = "0.6.2", default-features = false }
eyre = "0.6.8"
log = "0.4.20"
rsonpath-lib = { package = "rsonpath-lib", version = "0.6.0", default-features = false }
simple_logger = "4.2.0"

[build-dependencies]
rustflags = { version = "0.1.4" }
vergen = { version = "8.2.4", features = ["cargo", "git", "gitcl", "rustc"] }

[dev-dependencies]
trycmd = "0.14.17"

[features]
default = ["simd"]
simd = ["rsonpath-lib/simd"]
