name: "Nix Shell Build"
on:
  pull_request:
    branches: ["main", "nix"]
  push:
    branches: ["main", "nix"]

permissions:
  contents: read

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          submodules: true
      - uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: rrbutani/use-nix-shell-action@59a52b2b9bbfe3cc0e7deb8f9059abe37a439edf # v1.1.0
        with:
          file: shell.nix
      - name: Build
        run: just build
