name: rsonpath-test codegen

on:
  workflow_call:
    outputs:
      artifact-name:
        description: Name of the produced artifact.
        value: rsonpath-test-documents
      artifact-path:
        description: Path to which the artifact should be extracted.
        value: crates/rsonpath-lib/tests/documents

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RSONPATH_ENABLE_TEST_CODEGEN: 1
  CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG: "true"

permissions:
  contents: read

jobs:
  # Run the test codegen build step once and save the artifact to be used for all other steps.
  # This cuts down on CI time, since otherwise we'd regenerate tests on every step of the feature powerset test run.
  test-gen:
    name: Generate rsonpath-test cases
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: Install lld
        run: sudo apt install lld
      - name: Checkout sources
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          submodules: true
      - name: Install Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8 # master
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
      - name: Override toolchain
        run: rustup override set stable
      - name: Cache restore (Cargo)
        id: cache-restore-cargo
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: x86_64-unknown-linux-gnu-x86_64-unknown-linux-gnu--cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Build with test codegen
        id: build-test-codegen
        run: cargo build -p rsonpath-test -vv
      - name: Upload generated tests as artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: rsonpath-test-documents
          path: crates/rsonpath-lib/tests/documents
          retention-days: 1
